services:
   sPreus:
   image: preus:1.0
   expose:
      - "80"
   environment:
      - HOST_NAME=pj9f4a12-alseba.clotfje.net
   networks:
      - xPj9f4a12

sDc:
   image: nginx:latest
   container_name: cPartit
   volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
   depends_on:
      - sLlauna
   ports:
      - "80:8000"
   networks:
      - xPj9f4a12

networks:
 xPj9f4a12:
 name: pj9f4a12
 driver: bridge
